#ifndef curlexample_H
#define curlexample_H

/* Some cross-platform definitions generated by autotools */
#if HAVE_CONFIG_H
#  include <config.h>
#endif /* HAVE_CONFIG_H */
#if HAVE_CURL_H
#include "curl.h"
#endif /* HAVE_CURL_H */

#endif /* curlexample_H */
